-- J The Divine Eco Valley
-- Development & Demo Seed Data
-- Note: These records are designated development/sample items for testing and demonstration.
-- They can be easily replaced or supplemented with verified client catalog items.

INSERT INTO public.products (
    name,
    slug,
    description,
    short_description,
    category,
    religion_or_cultural_use,
    occasion,
    materials,
    base_material,
    image_url,
    gallery_images,
    featured,
    active,
    sort_order
) VALUES
(
    'Sample Royal Cardamom Wedding Garland',
    'sample-royal-cardamom-wedding-garland',
    'A majestic handcrafted garland woven with select unbroken green cardamom pods, accented with whole nutmeg, star anise, and golden silk accents. Formulated specifically for traditional Indian and multicultural wedding ceremonies, bride and groom varmala exchanges, and ceremonial wedding stages. The natural fragrant spice weave offers remarkable resilience and an unforgettable sensory presence.',
    'Exquisite bridal garland woven with premium green cardamom pods, whole nutmeg, and fine botanical highlights.',
    'Weddings',
    'Hindu and multicultural wedding traditions (Varmala / Jaimala rituals)',
    'Wedding Ceremonies, Bride/Groom Varmala, Reception Stage',
    ARRAY['Whole Green Cardamom', 'Nutmeg', 'Star Anise', 'Botanical Twine', 'Natural Silk Accents'],
    'Whole Green Cardamom',
    '/images/products/royal-cardamom-wedding.jpg',
    ARRAY['/images/products/royal-cardamom-wedding.jpg', '/images/products/royal-cardamom-wedding-detail.jpg', '/images/products/cardamom-macro.jpg'],
    true,
    true,
    1
),
(
    'Sample Vedic Cardamom & Nut Ceremony Garland',
    'sample-vedic-cardamom-nut-ceremony-garland',
    'Created with reverence for traditional temple pujas, sacred sanctum dedications, and ancestral invocations. Each cardamom pod is hand-sorted for uniform size and colour, paired with whole betel nuts and polished dry spices, strung onto pure natural cotton cord in accordance with customary ceremonial craftsmanship.',
    'Reverently assembled cardamom and sacred nut garland for temple ceremonies and sanctum pujas.',
    'Religious & Spiritual',
    'Sanatana Dharma puja rituals, temple sanctums, homams, and spiritual dedications',
    'Puja Ceremonies, Temple Invocations, Griha Pravesh',
    ARRAY['Grade-A Cardamom Pods', 'Whole Betel Nuts', 'Cloves', 'Natural Unbleached Cotton Cord'],
    'Grade-A Cardamom Pods',
    '/images/products/vedic-ceremony-garland.jpg',
    ARRAY['/images/products/vedic-ceremony-garland.jpg', '/images/products/cardamom-macro.jpg'],
    true,
    true,
    2
),
(
    'Sample Sanctum Door & Interior Garland',
    'sample-sanctum-door-interior-garland',
    'Designed for home portals, prayer altar backdrops, and peaceful interior niches. Combines natural cardamom pods with aromatic clove tassels, dried botanicals, and hand-turned woody spice beads that imbue living spaces with organic texture and subtle natural spice aroma.',
    'Aromatic cardamom and clove portal garland designed for home entryways and tranquil prayer spaces.',
    'Home & Interior',
    'Auspicious home adornment, prayer rooms, entryway torans',
    'Home Decor, Altar Backdrop, Festival Portal Accent',
    ARRAY['Sun-dried Cardamom Pods', 'Whole Cloves', 'Dried Botanical Flake', 'Jute Cord'],
    'Sun-dried Cardamom Pods',
    '/images/products/sanctum-interior-garland.jpg',
    ARRAY['/images/products/sanctum-interior-garland.jpg'],
    true,
    true,
    3
),
(
    'Sample Celebration Harvest Spice Garland',
    'sample-celebration-harvest-spice-garland',
    'A vibrant cultural celebration garland celebrating regional Indian harvest milestones and community gatherings. Features layered concentric cardamom tiers balanced with dried mace, cinnamon scrolls, and golden natural reed rosettes.',
    'Multi-tiered festive spice garland celebrating cultural gatherings and regional harvest milestones.',
    'Festivals & Cultural',
    'Harvest celebrations, cultural programs, festival processions',
    'Diwali, Pongal/Sankranti, Navratri, Cultural Pageants',
    ARRAY['Select Cardamom', 'Cinnamon Scrolls', 'Dried Mace', 'Golden Grass Weaves'],
    'Select Cardamom',
    '/images/products/harvest-spice-garland.jpg',
    ARRAY['/images/products/harvest-spice-garland.jpg'],
    false,
    true,
    4
),
(
    'Sample Grand Hospitality Welcome Garland',
    'sample-grand-hospitality-welcome-garland',
    'Crafted for luxury hotels, heritage resorts, and high-level corporate reception ceremonies. Features an elongated graceful contour that drapes comfortably over international dignitaries and guest arrivals, emitting a welcoming fresh spice fragrance.',
    'Graceful botanical welcome garland for luxury resorts, VIP receptions, and hospitality greetings.',
    'Hospitality',
    'Traditional Indian guest welcome (Atithi Devo Bhava) and diplomatic felicitations',
    'Resort Welcomes, VIP Felicitation, Dignitary Protocol',
    ARRAY['Extra-Bold Green Cardamom', 'Star Anise', 'Polished Wood Nuts', 'Gold Thread Weave'],
    'Extra-Bold Green Cardamom',
    '/images/products/hospitality-welcome-garland.jpg',
    ARRAY['/images/products/hospitality-welcome-garland.jpg'],
    true,
    true,
    5
),
(
    'Sample Regal Heritage Spice Gift Garland',
    'sample-regal-heritage-spice-gift-garland',
    'Presented in an eco-friendly handcrafted rigid presentation case. This ceremonial keepsake garland embodies timeless Indian artisan heritage, suitable for celebratory corporate gifting, anniversary celebrations, and international diplomatic tokens.',
    'Heritage gift garland presented in an export-ready bespoke case for prestigious occasions.',
    'Gifting',
    'Auspicious gifting, diplomatic exchange, heirloom milestones',
    'Festive Gifting, Corporate Tokens, Milestone Celebrations',
    ARRAY['Premium Cardamom Pods', 'Whole Nutmeg', 'Polished Cinnamon Rings', 'Cotton-Silk Cord'],
    'Premium Cardamom Pods',
    '/images/products/heritage-gift-garland.jpg',
    ARRAY['/images/products/heritage-gift-garland.jpg'],
    true,
    true,
    6
),
(
    'Sample Ivory Clove & Cardamom Bridal Garland',
    'sample-ivory-clove-cardamom-bridal-garland',
    'An intricate dual-strand bridal garland interleaving pale cardamom pods with fragrant clove rosettes and delicate mother-of-pearl botanical touches. Engineered for feather-light wear during extended wedding rites.',
    'Intricate dual-strand wedding garland interleaving cardamom pods with clove rosettes.',
    'Weddings',
    'Bridal wedding ceremonies, Anand Karaj, Vedic marriage vows',
    'Wedding Ceremonies, Bridal Attire, Portrait Sessions',
    ARRAY['Pale Cardamom Pods', 'Whole Hand-picked Cloves', 'Dried Seed Pods', 'Silk Ribbons'],
    'Pale Cardamom Pods',
    '/images/products/bridal-clove-cardamom.jpg',
    ARRAY['/images/products/bridal-clove-cardamom.jpg'],
    false,
    true,
    7
),
(
    'Sample Devotional Temple Sanctum Garland',
    'sample-devotional-temple-sanctum-garland',
    'A heavy-density ceremonial garland specifically proportioned for deity adornment, temple vigraha alankaram, and sacred sanctum installations. Built with reinforced organic cord to sustain prolonged devotional display.',
    'Heavy-density ceremonial cardamom garland tailored for temple vigraha and sanctum alankaram.',
    'Religious & Spiritual',
    'Temple sanctum vigraha alankaram, deity decoration, annual brahmotsavam',
    'Temple Festivals, Deity Abhishekam & Alankaram',
    ARRAY['Jumbo Green Cardamom', 'Holy Basil Stems', 'Whole Cloves', 'Reinforced Cotton Thread'],
    'Jumbo Green Cardamom',
    '/images/products/devotional-temple-garland.jpg',
    ARRAY['/images/products/devotional-temple-garland.jpg'],
    false,
    true,
    8
)
ON CONFLICT (slug) DO NOTHING;
